# Boolean Indexing

In [1]:
import numpy as np

In [9]:
names=np.array(['Hamza','Mutayyab','Nauman','Affan','Umama','Kashan','Rabia'])

In [10]:
data = np.random.randn(7,4)

In [11]:
names

array(['Hamza', 'Mutayyab', 'Nauman', 'Affan', 'Umama', 'Kashan', 'Rabia'],
      dtype='<U8')

In [12]:
data

array([[-1.84872964, -1.90552358, -0.27392335,  0.12633728],
       [-1.68279497, -0.08608966, -0.29811859,  0.21924437],
       [-0.30562998,  0.06732854,  0.60649767,  1.05461182],
       [-1.68307184,  0.01678305, -1.62292358,  0.57617652],
       [-0.84955186, -1.29544775, -0.47673191, -0.85644082],
       [-0.11028838, -0.76967093, -0.52585154, -1.68663836],
       [ 0.57242367,  0.53754845,  0.55047709,  2.79860538]])

In [13]:
names == 'Hamza'

array([ True, False, False, False, False, False, False])

In [15]:
data[names == 'Rabia']

array([[0.57242367, 0.53754845, 0.55047709, 2.79860538]])

In [16]:
data[names != "Mutayyab"]

array([[-1.84872964, -1.90552358, -0.27392335,  0.12633728],
       [-0.30562998,  0.06732854,  0.60649767,  1.05461182],
       [-1.68307184,  0.01678305, -1.62292358,  0.57617652],
       [-0.84955186, -1.29544775, -0.47673191, -0.85644082],
       [-0.11028838, -0.76967093, -0.52585154, -1.68663836],
       [ 0.57242367,  0.53754845,  0.55047709,  2.79860538]])

In [20]:
data[names == "Mutayyab",1:]

array([[-0.08608966, -0.29811859,  0.21924437]])

In [21]:
data

array([[-1.84872964, -1.90552358, -0.27392335,  0.12633728],
       [-1.68279497, -0.08608966, -0.29811859,  0.21924437],
       [-0.30562998,  0.06732854,  0.60649767,  1.05461182],
       [-1.68307184,  0.01678305, -1.62292358,  0.57617652],
       [-0.84955186, -1.29544775, -0.47673191, -0.85644082],
       [-0.11028838, -0.76967093, -0.52585154, -1.68663836],
       [ 0.57242367,  0.53754845,  0.55047709,  2.79860538]])

In [22]:
names != "Hamza"

array([False,  True,  True,  True,  True,  True,  True])

In [25]:
data[~(names == "Hamza")] 

array([[-1.68279497, -0.08608966, -0.29811859,  0.21924437],
       [-0.30562998,  0.06732854,  0.60649767,  1.05461182],
       [-1.68307184,  0.01678305, -1.62292358,  0.57617652],
       [-0.84955186, -1.29544775, -0.47673191, -0.85644082],
       [-0.11028838, -0.76967093, -0.52585154, -1.68663836],
       [ 0.57242367,  0.53754845,  0.55047709,  2.79860538]])

In [26]:
cond = names == "Hamza"

In [28]:
data[cond]

array([[-1.84872964, -1.90552358, -0.27392335,  0.12633728]])

In [31]:
mask =(names =="Hamza")|(names =="Mutayyab")

In [32]:
mask

array([ True,  True, False, False, False, False, False])

data

In [35]:
data[mask]

array([[-1.84872964, -1.90552358, -0.27392335,  0.12633728],
       [-1.68279497, -0.08608966, -0.29811859,  0.21924437]])

In [36]:
data < 0

array([[ True,  True,  True, False],
       [ True,  True,  True, False],
       [ True, False, False, False],
       [ True, False,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

In [37]:
data[data < 0]

array([-1.84872964, -1.90552358, -0.27392335, -1.68279497, -0.08608966,
       -0.29811859, -0.30562998, -1.68307184, -1.62292358, -0.84955186,
       -1.29544775, -0.47673191, -0.85644082, -0.11028838, -0.76967093,
       -0.52585154, -1.68663836])

In [38]:
data

array([[-1.84872964, -1.90552358, -0.27392335,  0.12633728],
       [-1.68279497, -0.08608966, -0.29811859,  0.21924437],
       [-0.30562998,  0.06732854,  0.60649767,  1.05461182],
       [-1.68307184,  0.01678305, -1.62292358,  0.57617652],
       [-0.84955186, -1.29544775, -0.47673191, -0.85644082],
       [-0.11028838, -0.76967093, -0.52585154, -1.68663836],
       [ 0.57242367,  0.53754845,  0.55047709,  2.79860538]])

In [43]:
data[data < 0]=7

In [44]:
data

array([[0.        , 0.        , 0.        , 0.12633728],
       [0.        , 0.        , 0.        , 0.21924437],
       [0.        , 0.06732854, 0.60649767, 1.05461182],
       [0.        , 0.01678305, 0.        , 0.57617652],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.57242367, 0.53754845, 0.55047709, 2.79860538]])

# Fancy indexing

In [45]:
arr = np.empty((8,4))

In [46]:
for i in range(8):
    arr[i]=i

In [47]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [51]:
arr[4]

array([4., 4., 4., 4.])

In [52]:
arr[[4,6]]

array([[4., 4., 4., 4.],
       [6., 6., 6., 6.]])

In [53]:
arr[[4,6],2:]

array([[4., 4.],
       [6., 6.]])

In [55]:
arr = np.arange(32).reshape((8,4))

In [56]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [57]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [58]:
arr[[1,5,7,2]][:,[0,3,1,2]]
#1[0,3,1,2],5[0,3,1,2],7[0,1,3,2],2[0,3,1,2]
#[(1,0),(1,3),(1,1),(1,2)] and so on 

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# Transposing Arrays and Swapping Axes

In [59]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [60]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [61]:
arr = np.random.randn(7)*5

In [62]:
arr

array([ 1.06878383,  0.31602866, -1.39864746, -4.26056002, -2.73323524,
        6.44666076,  2.59688948])

In [63]:
remainder, whole_part = np.modf(arr)

In [64]:
remainder

array([ 0.06878383,  0.31602866, -0.39864746, -0.26056002, -0.73323524,
        0.44666076,  0.59688948])

In [65]:
whole_part

array([ 1.,  0., -1., -4., -2.,  6.,  2.])

In [66]:
np.sqrt(arr)

C:\Users\Mirza Hamza\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([1.03382002, 0.56216427,        nan,        nan,        nan,
       2.53902752, 1.61148673])

# Array-Oriented Programming with Arrays

In [68]:
points = np.arange(-5,5,0.01)# 1000 equally spaced points

In [69]:
xs,ys = np.meshgrid(points,points)

In [70]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [71]:
z = np.sqrt(xs**2+ys**2)

In [72]:
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

# Expressions & conditions

In [73]:
names

array(['Hamza', 'Mutayyab', 'Nauman', 'Affan', 'Umama', 'Kashan', 'Rabia'],
      dtype='<U8')

In [74]:
name=set(names)

In [75]:
name

{'Affan', 'Hamza', 'Kashan', 'Mutayyab', 'Nauman', 'Rabia', 'Umama'}

In [76]:
sorted(set(names))

['Affan', 'Hamza', 'Kashan', 'Mutayyab', 'Nauman', 'Rabia', 'Umama']

In [77]:
arr=np.arange(15)

In [81]:
arr.reshape((5,-2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [82]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [83]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [85]:
ravel =arr.ravel()

In [86]:
flat=arr.flatten()

In [87]:
ravel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [88]:
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [89]:
ravel[2:8]= 0

In [90]:
ravel

array([ 0,  1,  0,  0,  0,  0,  0,  0,  8,  9, 10, 11, 12, 13, 14])

In [91]:
arr

array([ 0,  1,  0,  0,  0,  0,  0,  0,  8,  9, 10, 11, 12, 13, 14])

In [95]:
flat[2:9]=0

In [96]:
flat

array([ 0,  1,  0,  0,  0,  0,  0,  0,  0,  9, 10, 11, 12, 13, 14])

In [97]:
arr

array([ 0,  1,  0,  0,  0,  0,  0,  0,  8,  9, 10, 11, 12, 13, 14])

# Concetanation and splitting Arrays

In [98]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

In [99]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [102]:
np.concatenate([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [103]:
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [104]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [105]:
np.vstack([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [106]:
np.hstack([arr1,arr2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [107]:
splitt = np.arange(1,25).reshape(6,4)

In [108]:
splitt

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [110]:
np.split(splitt,3,axis=0)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]), array([[17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [111]:
np.vsplit(splitt,2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [112]:
np.hsplit(splitt,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]), array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [113]:
arr.repeat(3)

array([ 0,  0,  0,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  8,  8,  8,  9,  9,  9, 10, 10, 10, 11,
       11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14])

In [115]:
np.tile(arr,2)

array([ 0,  1,  0,  0,  0,  0,  0,  0,  8,  9, 10, 11, 12, 13, 14,  0,  1,
        0,  0,  0,  0,  0,  0,  8,  9, 10, 11, 12, 13, 14])

In [116]:
arr=np.array([1,2,3,4])
print(np.broadcast(arr,4))