In [1]:
import numpy as np

In [2]:
arr3d = np.arange(50).reshape(2,5,5)

In [3]:
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [4]:
arr3d[1,2,3]

38

In [6]:
arr3d[0,3,4]

19

In [7]:
arr3d[1,2:,1:3]

array([[36, 37],
       [41, 42],
       [46, 47]])

In [9]:
arr3d[0,2:4,4:]

array([[14],
       [19]])

In [11]:
arr3d[0,2:4,4]

array([14, 19])

In [12]:
arr3d[0:1,2:,4:]

array([[[14],
        [19],
        [24]]])

In [13]:
import pandas as pd

In [15]:
obj =  pd.Series([10,11,12,13])

In [16]:
obj

0    10
1    11
2    12
3    13
dtype: int64

In [17]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [18]:
obj.values

array([10, 11, 12, 13], dtype=int64)

In [20]:
obj1 = pd.Series([10,11,12,13],index=['a','b','c','d'])

In [21]:
obj1

a    10
b    11
c    12
d    13
dtype: int64

In [22]:
obj1.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [23]:
obj1['d']

13

In [25]:
obj1['c']=100

In [27]:
obj1

a     10
b     11
c    100
d     13
dtype: int64

In [28]:
obj1['z']=111

In [29]:
obj1

a     10
b     11
c    100
d     13
z    111
dtype: int64

In [33]:
index=[1,2,3,4]

In [50]:
obj2 = pd.Series(["iphone","Samsung","Huawei","Motorolla"],index = index)

In [ ]:
del obj1['c']

In [52]:
obj1

a     10
b     11
d     13
z    111
dtype: int64

In [54]:
obj2

1       iphone
2      Samsung
3       Huawei
4    Motorolla
dtype: object

In [55]:
obj2[4]

'Motorolla'

In [44]:
obj2[[3,5,1]]

3    Huawei
5       NaN
1    iphone
dtype: object

In [56]:
obj2[obj2 =="banana"]

Series([], dtype: object)

In [57]:
obj2*2

1          iphoneiphone
2        SamsungSamsung
3          HuaweiHuawei
4    MotorollaMotorolla
dtype: object

In [58]:
print("iphone"*5)

iphoneiphoneiphoneiphoneiphone


In [59]:
s1 = pd.Series([100,200,300,400,500],index = ["hun","2h","3h","4h","5h"])

In [60]:
s1

hun    100
2h     200
3h     300
4h     400
5h     500
dtype: int64

In [61]:
"6h" in s1

False

In [62]:
"2h" in s1

True

In [63]:
#Creating a series using python dictionary

In [76]:
d = {"Karach":7500,"Lahore":4500,"Islamabad":8000}

In [77]:
s2 =pd.Series(d)

In [78]:
s2

Karach       7500
Lahore       4500
Islamabad    8000
dtype: int64

In [79]:
e = ["Karachi","Lahore","Islamabad"]

In [80]:
s2 = pd.Series(d,index =e)

In [81]:
s2

Karachi         NaN
Lahore       4500.0
Islamabad    8000.0
dtype: float64

In [82]:
pd.isnull(s2)

Karachi       True
Lahore       False
Islamabad    False
dtype: bool

In [83]:
pd.notnull(s2)

Karachi      False
Lahore        True
Islamabad     True
dtype: bool

# Data Frames

In [120]:
data = {'state':["Karachi","lahore","Islamabad","Peshawar"],'year':[2000,2001,2002,2003],'pop':[1.5,1.7,3.6,2.4]}

In [121]:
df = pd.DataFrame(data)

In [122]:
df

state  year  pop
0    Karachi  2000  1.5
1     lahore  2001  1.7
2  Islamabad  2002  3.6
3   Peshawar  2003  2.4

In [123]:
df.shape

(4, 3)

In [124]:
df.head()#starting 5 shows

state  year  pop
0    Karachi  2000  1.5
1     lahore  2001  1.7
2  Islamabad  2002  3.6
3   Peshawar  2003  2.4

In [125]:
df.tail()#ending 5 shows

state  year  pop
0    Karachi  2000  1.5
1     lahore  2001  1.7
2  Islamabad  2002  3.6
3   Peshawar  2003  2.4

In [126]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
state    4 non-null object
year     4 non-null int64
pop      4 non-null float64
dtypes: float64(1), int64(1), object(1)
memory usage: 176.0+ bytes


In [127]:
pd.DataFrame(data,columns=['year','state','pop'])

year      state  pop
0  2000    Karachi  1.5
1  2001     lahore  1.7
2  2002  Islamabad  3.6
3  2003   Peshawar  2.4

In [128]:
df1=pd.DataFrame(data)

In [135]:
frame2 =  pd.DataFrame(data,columns=['year','state','pop'],index=['one','two','three','four'])

In [136]:
frame2

year      state  pop
one    2000    Karachi  1.5
two    2001     lahore  1.7
three  2002  Islamabad  3.6
four   2003   Peshawar  2.4

In [137]:
frame2.loc['two']

year       2001
state    lahore
pop         1.7
Name: two, dtype: object

In [140]:
frame2.iloc[2]

year          2002
state    Islamabad
pop            3.6
Name: three, dtype: object

In [142]:
frame2["year"]

one      2000
two      2001
three    2002
four     2003
Name: year, dtype: int64

In [144]:
frame2["state"]

one        Karachi
two         lahore
three    Islamabad
four      Peshawar
Name: state, dtype: object

In [145]:
frame2["pop"]

one      1.5
two      1.7
three    3.6
four     2.4
Name: pop, dtype: float64

In [150]:
frame2

year      state  pop
one    2000    Karachi  1.5
two    2001     lahore  1.7
three  2002  Islamabad  3.6
four   2003   Peshawar  2.4

In [155]:
frame2[["state","year"]]

state  year
one      Karachi  2000
two       lahore  2001
three  Islamabad  2002
four    Peshawar  2003

In [156]:
val = pd.Series([-1.2,-1.5,-1.7],index=["two","four","five"])

In [157]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [159]:
frame2['year'] = val

In [160]:
frame2

year      state  pop
one     NaN    Karachi  1.5
two    -1.2     lahore  1.7
three   NaN  Islamabad  3.6
four   -1.5   Peshawar  2.4

In [161]:
frame2.year[['one','three']]=[5,10]

C:\Users\Mirza Hamza\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [162]:
frame2

year      state  pop
one     5.0    Karachi  1.5
two    -1.2     lahore  1.7
three  10.0  Islamabad  3.6
four   -1.5   Peshawar  2.4