# Number python(Numpy)

In [ ]:
import numpy as np

In [2]:
a =np.array([2,3,4,5])

In [3]:
a*2

array([ 4,  6,  8, 10])

In [4]:
type(a)

numpy.ndarray

In [5]:
data=np.random.randn(2,3)
data

array([[-0.9733726 , -0.49779799,  0.0113847 ],
       [ 0.81180848, -0.93585554,  0.28545036]])

In [6]:
data1=np.arange(10)#range

In [7]:
data1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
data1.ndim#dimension 1-D vector

1

In [9]:
data.ndim#dimension 2-D Matrices.

2

In [10]:
data.shape#Matric order Row x column 

(2, 3)

In [13]:
c=np.array(100)#Scalar because there is no square bracket

In [14]:
c.ndim

0

In [15]:
c=np.array([[[100]]])#Number of square brackets create numbers of dimensions

In [17]:
c.ndim

3

In [18]:
c.shape

(1, 1, 1)

In [19]:
_3d = np.array([[[100,33,44],[3,11,90],[2,8,77]]])#3 dimensional matrices

In [20]:
_3d

array([[[100,  33,  44],
        [  3,  11,  90],
        [  2,   8,  77]]])

In [21]:
threeD = np.arange(64).reshape(4,4,4)

In [22]:
threeD

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [23]:
threeD = np.arange(30).reshape(3,5,2)#Here position for 3 is depth and postion for 5 and 2 is front

In [24]:
threeD

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [25]:
threeD = np.arange(30).reshape(2,5,3)

In [26]:
threeD

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [27]:
threeD.ndim

3

In [28]:
#element wise opeation
m1=np.arange(12).reshape(4,3)
m2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [29]:
m1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
m2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
m1.shape

(4, 3)

In [32]:
m2.shape

(4, 3)

In [33]:
m1+m2

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

In [34]:
m1-m2

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [35]:
m1/m2

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889],
       [0.9       , 0.90909091, 0.91666667]])

In [36]:
m1*m2

array([[  0,   2,   6],
       [ 12,  20,  30],
       [ 42,  56,  72],
       [ 90, 110, 132]])

In [37]:
m3 = np.arange(12).reshape(3,4)

In [38]:
m3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
m3.shape

(3, 4)

In [43]:
m1@m3#Mttrices multiplication operator @

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [44]:
print(m1.shape)
print(m3.shape)
m1@m3

(4, 3)
(3, 4)


array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [46]:
np.dot(m1,m3)#same like @

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [48]:
m1.dot(m3)#same like @

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [51]:
a=np.array([33,44.2,66],dtype="float32")

In [52]:
a

array([33. , 44.2, 66. ], dtype=float32)

In [53]:
a=np.array([33,44.2,66],dtype=np.float32)

In [54]:
a

array([33. , 44.2, 66. ], dtype=float32)

In [59]:
b=np.asarray(a,np.int32)

In [60]:
b

array([33, 44, 66])

In [62]:
b=np.asarray(a,"int32")

In [63]:
b

array([33, 44, 66])

In [65]:
np.ones([10,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [66]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [70]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [71]:
np.ones((3,4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [73]:
b=np.full((3,4),7)

In [74]:
b

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [76]:
j=np.ones_like(b)

In [77]:
j

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [78]:
j=np.zeros_like(b)

In [79]:
j

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [80]:
j=np.empty_like(b)

In [81]:
j

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [82]:
t=np.arange(36).reshape(6,6)

In [83]:
t

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [86]:
t[2,3]#indexing

15

In [87]:
t[2][3]

15

In [91]:
#t[r,c]
#t[--,--]
t[2:5,2:4]#slicing

array([[14, 15],
       [20, 21],
       [26, 27]])