In [2]:
import tensorflow as tf

In [3]:
from keras.datasets import mnist

Using TensorFlow backend.


In [4]:
(train_images, train_labels), (test_images,test_labels) = mnist.load_data()

11493376/11490434 [==============================] - 33s 3us/step


In [5]:
train_images.shape

(60000, 28, 28)

In [7]:
len(train_images)

60000

In [8]:
len(train_labels)

60000

In [9]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [10]:
test_images.shape

(10000, 28, 28)

In [11]:
len(test_labels)

10000

In [12]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [13]:
from keras import models
from keras import layers

In [14]:
network = models.Sequential()

In [15]:
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))

In [16]:
network.add(layers.Dense(10, activation='softmax'))

In [17]:
network

In [18]:
network.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])

In [19]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [20]:
from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [21]:
 network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 12s 197us/step - loss: 0.2589 - accuracy: 0.9249
Epoch 2/5
60000/60000 [==============================] - 8s 126us/step - loss: 0.1052 - accuracy: 0.9689
Epoch 3/5
60000/60000 [==============================] - 7s 124us/step - loss: 0.0694 - accuracy: 0.9791
Epoch 4/5
60000/60000 [==============================] - 7s 124us/step - loss: 0.0502 - accuracy: 0.9851
Epoch 5/5
60000/60000 [==============================] - 8s 125us/step - loss: 0.0375 - accuracy: 0.9885


In [22]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

10000/10000 [==============================] - 2s 201us/step


In [23]:
 print('test_acc:', test_acc)

test_acc: 0.9803000092506409


In [24]:
import numpy as np
a=np.arange(50).reshape(2,5,5)

In [25]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [26]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])